language: go

go:
  - 1.11.x

install:
  - go get github.com/shoenig/petrify/...
  - go get github.com/shoenig/mockery

script:
  - go generate ./...
  - go build ./...
  - go vet ./...
  - go test ./...

