language: go

go:
  - 1.11.x

install:
  - go get github.com/shoenig/petrify/...
  - go get github.com/shoenig/mockery3/v3
  - mkdir -p "$GOPATH/src/github.com/stretchr" && git clone http://github.com/stretchr/testify "$GOPATH/src/github.com/stretchr/testify"

script:
  - go generate ./...
  - go build ./...
  - go vet ./...
  - go test ./...

