language: go

go:
  - 1.12.5

install:
  - go get github.com/shoenig/petrify/...
  - go get github.com/gojuno/minimock/cmd/minimock/...

script:
  - go generate ./...
  - go build ./...
  - go vet ./...
  - go test -race ./...

services:
  - mysql


before_script:
  - mysql -e 'CREATE DATABASE modproxdb;'
