language: go

go:
  - 1.12.x

install:
  - echo "do nothing for install step"

script:
  - go generate ./...
  - go build ./...
  - go vet ./...
  - go test -race ./...

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE modproxdb;'
