version: '3.4'

services:
  mysql-registry:
    image: mysql/mysql-server:5.7
    container_name: modprox-mysql-registry
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
      - /tmp
    volumes:
      - ./sql/mysql-reg:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=modproxdb-reg
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    entrypoint:
      - /entrypoint.sh
      - mysqld

  mysql-proxy:
    image: mysql/mysql-server:5.7
    container_name: modprox-mysql-proxy
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql
      - /tmp
    volumes:
      - ./sql/mysql-prox:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=modproxdb-prox
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    entrypoint:
      - /entrypoint.sh
      - mysqld

# A fake datadog/statsd collector which prints metrics
# to standard out in your docker container
  fakeadog:
    image: johnstcn/fakeadog:latest
    container_name: modprox-fakeadog
    ports:
      - target: 8125
        published: 8125
        protocol: udp
        mode: host
    tmpfs:
      - /tmp
    environment:
      - HOST=0.0.0.0
      - PORT=8125
